### ISSUE TITLE
Document how sidecar is used

### ISSUE THREAD

**Issue by daviddias** [ipfs/testground#174] opened 2019-11-19 01:29 UTC
With #143, we need to have docs for:
- How sidecar works
- How to contribute/develop sidecar (e.g. every release, a new docker sidecar image needs to be pushed to docker hub)
- Docker hub credentials being 1password

**Comment by raulk** [comment] 2020-03-09 17:13
Duplicate of #221. Documented here: https://github.com/ipfs/testground/blob/master/docs/SIDECAR.md.

**Closed by raulk** 2020-03-09 17:13 UTC
