### ISSUE TITLE
Panic logging output on k8s

### ISSUE THREAD

**Issue by aschmahmann** [ipfs/testground#514] opened 2020-02-10 17:32 UTC
#### Version information:

The branch is based off of 003b47a2dbd91df272d3b29637479ab970f73a76. Updating to master now.

`kubectl describe` on the sidecar contains `docker-pullable://ipfs/testground@sha256:7ecd633ad5d8080567d5a85339187324593ad7905e1e4fd03238fb512e000a47 `

#### Description:

Ran the DHT tests on 150 nodes on k8s and one of them failed with the following panic.

```
panic: couldn't open sink "/outputs/run.out": open /outputs/run.out: no such file or directory

goroutine 1 [running]:
github.com/ipfs/testground/sdk/runtime.(*logger).init(0xc0001bcb80)
        /sdk/runtime/logger.go:60 +0x6eb
github.com/ipfs/testground/sdk/runtime.newLogger(...)
        /sdk/runtime/logger.go:21
github.com/ipfs/testground/sdk/runtime.ParseRunEnv(0xc00001f200, 0x24, 0x24, 0x1a, 0xc000242630, 0x30)
        /sdk/runtime/runenv.go:217 +0x77c
github.com/ipfs/testground/sdk/runtime.CurrentRunEnv(0x8)
        /sdk/runtime/runenv.go:185 +0x27
github.com/ipfs/testground/sdk/runtime.Invoke(0xd0a028)
        /sdk/runtime/runner.go:12 +0x37
main.main()
        /plan/main.go:16 +0x2d
```

**Comment by nonsense** [comment] 2020-02-10 17:51
This image is from `"Created": "2020-02-10T12:48:27.732778773Z",` so this most probably is currently broken on `master`.

**Comment by raulk** [comment] 2020-02-13 11:00
@nonsense this looks like k8s didn't properly mount the `/outputs` volume on this pod?

**Comment by raulk** [comment] 2020-02-13 11:00
"file not found" here can only mean that the `/outputs` directory is missing.

**Comment by aschmahmann** [comment] 2020-02-13 11:09
This error has occurred also for the `run.err` asset as well as for all custom structured assets. Here is an error emitted for run.err.

This is bizarre since run.err exists in the same directory as run.out which should have already been created successfully. Maybe S3fs has some problems. I've been hacking around this by retrying on failure with reasonable success.

{"ts":1581576468083607285,"msg":"","group_id":"cypress","run_id":"13fbf2667a03","event":{"type":"finish","outcome":"failed","error":"open /outputs/run.err: no such file or directory","stacktrace":"goroutine 1 [running]:\nruntime/debug.Stack(0xc32a30, 0x2, 0xc000257cc0)\n\t/usr/local/go/src/runtime/debug/stack.go:24 +0x9d\ngithub.com/ipfs/testground/sdk/runtime.(*logger).RecordCrash(0xc000272ba0, 0xb62a60, 0xc0002768a0)\n\t/sdk/runtime/output.go:170 +0xa2\ngithub.com/ipfs/testground/sdk/runtime.Invoke(0xd8afe0)\n\t/sdk/runtime/runner.go:17 +0xe0\nmain.main()\n\t/plan/main.go:16 +0x2d\n"}}

**Comment by nonsense** [comment] 2020-02-13 11:27
@aschmahmann please post your `composition` and your run config, so that we can reproduce this as well.

**Comment by raulk** [comment] 2020-02-20 22:52
@aschmahmann reports he hasn't seen this in a while. Closing the issue; reopen it if resurfaces! (and please post the composition)

**Closed by raulk** 2020-02-20 22:52 UTC
Labels: bug
