### ISSUE TITLE
Tests hang when using Subscriptions

### ISSUE THREAD

**Issue by aschmahmann** [ipfs/testground#684] opened 2020-03-15 21:41 UTC
I'm having trouble nailing down exactly what's going on, but sometimes test instances will finish running but will not close and return "OK" when using Subscriptions, instead they just hang even beyond the test timeout duration.

Happy to provide more context upon request.

@raulk @coryschwartz

**Comment by aschmahmann** [comment] 2020-03-15 23:31
Take a look at the branch at https://github.com/ipfs/testground/tree/bug/subs. I added a test that copies how the DHT test in master (i.e. not touched by me) utilizes subscriptions. Perhaps the test is misusing the subscription, but either way it'd be great to know.

**Comment by aschmahmann** [comment] 2020-03-16 14:34
@raulk `testground run s benchmarks/stagingsubs --runner local:docker --builder docker:go --instances 16`

**Comment by raulk** [comment] 2020-03-16 14:43
@aschmahmann something that immediately strikes me is that this [goroutine is not capturing the `tst` variable](https://github.com/ipfs/testground/commit/2ee4d67f7d8717567dab43d9dd405ca855c342ed#diff-90b7f8dd0c33b261618cf6d93af8c61dR374-R385). So by the time the pointer gets dereferenced, it could be pointing at the next test spec, which would make the byte slice comparison fail and would lead to never closing the done channel, thus the test would hang.

**Comment by raulk** [comment] 2020-03-16 14:44
This could be a test bug; not sure how faithfully it replicates the behaviour in the DHT test plan where you've noticed this.

**Comment by raulk** [comment] 2020-03-16 14:46
Actually, I'm wrong. Still looking.

**Comment by raulk** [comment] 2020-03-16 15:32
Found the bug, and pushed an annotated commit here: https://github.com/ipfs/testground/commit/e0bb6cb81cdc07270d06052394268734c6afc2fd.

The root cause is twofold:

* we're not cancelling the subscription when we've stopped consuming, therefore we exhaust file descriptors (each subscription holds up a Redis connection) -- this is a test plan bug.
* the test instances are artificially kept alive by this bug: https://github.com/ipfs/testground/issues/637.

**Closed** 2020-03-16 15:32 UTC
